# Generated by Django 5.2.1 on 2025-06-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coming_soon',
            field=models.BooleanField(default=False),
        ),
    ]
