# Generated by Django 5.2.1 on 2025-08-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='week_Deals',
            field=models.BooleanField(default=False),
        ),
    ]
