# Generated by Django 5.2.1 on 2025-06-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='lats_name',
            new_name='last_name',
        ),
    ]
